/**
 * Pipeline Module
 *
 * Unified entry point for the property data pipeline.
 * Stages: Fetch -> Parse -> Enrich -> Score -> Assess -> View -> Output
 */

// Re-export assess stage
export { calculateAssessedScore, normalizeAssessment } from './assess/index.js';
// Re-export enrich stage
export {
	type AreaEnrichmentResult,
	applyEpcToListing,
	type BroadbandResult,
	closeAreaDbs,
	type EnrichNotesResult,
	type EnrichOptions,
	type EnrichResult,
	type EpcApiResult,
	type EpcEnrichmentResult,
	type EpcRecord,
	enrichListing,
	enrichListingArea,
	enrichListingNotes,
	enrichListings,
	enrichWithEpc,
	extractNotes,
	fetchEpcByPostcode,
	lookupBroadband,
	lookupPostcode,
} from './enrich/index.js';
// Re-export fetch stage
export {
	type ApiSearchParams,
	type ApiSearchResult,
	buildListingUrl,
	buildSearchUrl,
	DEFAULT_DELAY_MS,
	type FetchResult,
	fetchWithRateLimit,
	type LocationLookupResult,
	lookupLocation,
	resetRateLimiter,
	searchListingsApi,
	setFetchDelay,
} from './fetch/index.js';
// Re-export output stage
export {
	buildNotionProperties,
	createNotionPage,
	type NotionConfig,
	queryExistingPages,
	updateNotionPage,
	validateDatabase,
} from './output/index.js';
// Re-export parse stage
export {
	extractNextData,
	extractPageModel,
	getPath,
	isArray,
	isNumber,
	isObject,
	isString,
	type ParseResult,
	parseListedDate,
	parsePrice,
	type ScrapeResult,
	type SearchScrapeResult,
	sanitizeForAi,
	sanitizeHtml,
	scrapeListing,
	scrapeSearchResults,
	transformPageModel,
} from './parse/index.js';

// Re-export score stage
export {
	type AffordabilityConfig,
	aggregateScores,
	broadbandUtility,
	buildPercentileContext,
	buildScoringContext,
	type CompositeScores,
	type CompositeWeights,
	type ConfidenceMetadata,
	calculateAffordability,
	calculateCompositeImpact,
	calculateConfidence,
	calculateLiveability,
	calculateLocation,
	calculatePenalties,
	calculatePercentile,
	calculateRawScore,
	calculateStats,
	clamp,
	DEFAULT_SCORING_CONFIG,
	describeConfidence,
	detectGardenType,
	detectHeatingType,
	detectPetPolicy,
	type EpcBand,
	epcBandToNumeric,
	explainPenalties,
	exponentialDecay,
	extractNameFromAddress,
	extractNameFromRegion,
	extractRawFactors,
	extractRegionName,
	floorAreaUtility,
	type GardenType,
	getAffordabilityBreakdown,
	getHeatingCostEstimate,
	getLiveabilityBreakdown,
	getLocationBreakdown,
	getNearestStationDistance,
	type HeatingType,
	inverseLerp,
	type LiveabilityConfig,
	type LocationConfig,
	lerp,
	type NormalizedFactors,
	normalizeFactors,
	normalizePropertyType,
	type PenaltyConfig,
	type PenaltyMultipliers,
	type PercentileContext,
	type PetPolicy,
	percentileToLabel,
	type RawFactors,
	roundTo,
	type ScoreContextMetadata,
	type ScoredListing,
	type ScoreFactors,
	type Scores,
	type ScoringConfig,
	type ScoringContext,
	type ScoringResult,
	type StatsSummary,
	scoreListings,
	scoreListingsWithConfig,
	scoreSingleListing,
	sigmoid,
	sigmoidThreshold,
	stationProximityUtility,
	weightedArithmeticMean,
	weightedGeometricMean,
} from './score/index.js';

// Re-export view stage
export {
	computeRegionStats,
	computeStats,
	filterByMinScore,
	filterByRegion,
	filterByType,
	filterListings,
	findListingById,
	formatStation,
	formatTableRow,
	type ListingStats,
	queryListings,
	type RegionSortField,
	type RegionStats,
	type SortField,
	sortListings,
	sortRegionStats,
	type TableRow,
	truncate,
	type ViewerFilters,
} from './view/index.js';
