/**
 * Note extraction patterns and sort order.
 */

/**
 * Pattern definition for note extraction
 */
export type NotePattern = {
	pattern: RegExp;
	extract: (match: RegExpMatchArray) => string | null;
};

/**
 * Patterns for extracting useful notes from descriptions
 */
export const NOTE_PATTERNS: NotePattern[] = [
	// Condition signals
	{ pattern: /recently\s+refurbished/gi, extract: () => 'recently refurbished' },
	{ pattern: /newly\s+refurbished/gi, extract: () => 'newly refurbished' },
	{ pattern: /fully\s+refurbished/gi, extract: () => 'fully refurbished' },
	{ pattern: /recently\s+renovated/gi, extract: () => 'recently renovated' },
	{ pattern: /newly\s+renovated/gi, extract: () => 'newly renovated' },
	{ pattern: /new\s+kitchen/gi, extract: () => 'new kitchen' },
	{ pattern: /recently\s+fitted\s+kitchen/gi, extract: () => 'recently fitted kitchen' },
	{ pattern: /new\s+bathroom/gi, extract: () => 'new bathroom' },
	{ pattern: /dated\s+decor/gi, extract: () => 'dated decor' },
	{ pattern: /needs\s+updating/gi, extract: () => 'needs updating' },
	{ pattern: /in\s+need\s+of\s+modernisation/gi, extract: () => 'needs updating' },
	{ pattern: /freshly\s+painted/gi, extract: () => 'freshly painted' },
	{ pattern: /freshly\s+decorated/gi, extract: () => 'freshly decorated' },
	{ pattern: /brand\s+new/gi, extract: () => 'brand new' },
	{ pattern: /new\s+build/gi, extract: () => 'new build' },
	{ pattern: /modern\s+kitchen/gi, extract: () => 'modern kitchen' },
	{ pattern: /fitted\s+kitchen/gi, extract: () => 'fitted kitchen' },

	// Garden details with measurements
	{ pattern: /south[- ]?facing\s+garden(?:\s+(?:approx(?:imately)?\.?\s*)?(\d+)\s*(?:ft|feet|m))?/gi, extract: (m) => (m[1] ? `south-facing garden ${m[1]}ft` : 'south-facing garden') },
	{ pattern: /west[- ]?facing\s+garden(?:\s+(?:approx(?:imately)?\.?\s*)?(\d+)\s*(?:ft|feet|m))?/gi, extract: (m) => (m[1] ? `west-facing garden ${m[1]}ft` : 'west-facing garden') },
	{ pattern: /east[- ]?facing\s+garden/gi, extract: () => 'east-facing garden' },
	{ pattern: /north[- ]?facing\s+garden/gi, extract: () => 'north-facing garden' },
	{ pattern: /enclosed\s+(?:rear\s+)?garden/gi, extract: () => 'enclosed garden' },
	{ pattern: /private\s+(?:rear\s+)?garden/gi, extract: () => 'private garden' },
	{ pattern: /rear\s+garden(?:\s+(?:approx(?:imately)?\.?\s*)?(\d+)\s*(?:ft|feet|m))?/gi, extract: (m) => (m[1] ? `rear garden ${m[1]}ft` : 'rear garden') },
	{ pattern: /front\s+(?:and\s+)?rear\s+gardens?/gi, extract: () => 'front and rear gardens' },
	{ pattern: /mature\s+garden/gi, extract: () => 'mature garden' },
	{ pattern: /landscaped\s+garden/gi, extract: () => 'landscaped garden' },
	{ pattern: /large\s+garden/gi, extract: () => 'large garden' },
	{ pattern: /patio\s+(?:and\s+)?(?:lawn|garden)/gi, extract: () => 'patio and lawn' },
	{ pattern: /decked\s+(?:area|garden|patio)/gi, extract: () => 'decked area' },
	{ pattern: /low\s+maintenance\s+garden/gi, extract: () => 'low maintenance garden' },
	{ pattern: /courtyard\s+garden/gi, extract: () => 'courtyard garden' },
	{ pattern: /garden\s+shed/gi, extract: () => 'garden shed' },
	{ pattern: /summer\s+house/gi, extract: () => 'summer house' },
	{ pattern: /outbuilding/gi, extract: () => 'outbuilding' },

	// Parking
	{ pattern: /driveway\s+(?:parking\s+)?(?:for\s+)?(\d+)\s+(?:cars?|vehicles?)/gi, extract: (m) => `driveway for ${m[1]} cars` },
	{ pattern: /driveway\s+parking/gi, extract: () => 'driveway parking' },
	{ pattern: /off[- ]?road\s+parking/gi, extract: () => 'off-road parking' },
	{ pattern: /off[- ]?street\s+parking/gi, extract: () => 'off-street parking' },
	{ pattern: /private\s+parking/gi, extract: () => 'private parking' },
	{ pattern: /allocated\s+parking/gi, extract: () => 'allocated parking' },
	{ pattern: /parking\s+space/gi, extract: () => 'parking space' },
	{ pattern: /permit\s+parking(?:\s+only)?/gi, extract: () => 'permit parking' },
	{ pattern: /(?:single|double)\s+garage/gi, extract: (m) => m[0]?.toLowerCase() ?? 'garage' },
	{ pattern: /\bgarage\b/gi, extract: () => 'garage' },
	{ pattern: /carport/gi, extract: () => 'carport' },
	{ pattern: /on[- ]?street\s+parking/gi, extract: () => 'on-street parking' },

	// Useful features
	{ pattern: /bay\s+window/gi, extract: () => 'bay windows' },
	{ pattern: /period\s+features?/gi, extract: () => 'period features' },
	{ pattern: /original\s+features?/gi, extract: () => 'original features' },
	{ pattern: /high\s+ceilings?/gi, extract: () => 'high ceilings' },
	{ pattern: /utility\s+room/gi, extract: () => 'utility room' },
	{ pattern: /en[- ]?suite/gi, extract: () => 'en-suite' },
	{ pattern: /downstairs\s+(?:wc|toilet|cloakroom)/gi, extract: () => 'downstairs wc' },
	{ pattern: /separate\s+(?:wc|toilet)/gi, extract: () => 'separate wc' },
	{ pattern: /conservatory/gi, extract: () => 'conservatory' },
	{ pattern: /loft\s+(?:room|conversion|space)/gi, extract: () => 'loft room' },
	{ pattern: /attic\s+(?:room|conversion|space)/gi, extract: () => 'attic room' },
	{ pattern: /cellar/gi, extract: () => 'cellar' },
	{ pattern: /basement/gi, extract: () => 'basement' },
	{ pattern: /open[- ]?plan(?:\s+(?:living|kitchen|lounge))?/gi, extract: () => 'open-plan living' },
	{ pattern: /integrated\s+appliances/gi, extract: () => 'integrated appliances' },
	{ pattern: /fitted\s+wardrobes?/gi, extract: () => 'fitted wardrobes' },
	{ pattern: /built[- ]?in\s+wardrobes?/gi, extract: () => 'built-in wardrobes' },
	{ pattern: /walk[- ]?in\s+wardrobe/gi, extract: () => 'walk-in wardrobe' },
	{ pattern: /log\s+burner/gi, extract: () => 'log burner' },
	{ pattern: /wood\s+(?:burning\s+)?(?:stove|burner)/gi, extract: () => 'wood burner' },
	{ pattern: /open\s+fire(?:place)?/gi, extract: () => 'open fireplace' },
	{ pattern: /feature\s+fireplace/gi, extract: () => 'feature fireplace' },
	{ pattern: /exposed\s+(?:brick|beams?|stone)/gi, extract: (m) => `exposed ${m[0]?.split(/\s+/)[1]?.toLowerCase() ?? 'features'}` },
	{ pattern: /wooden\s+(?:floors?|flooring)/gi, extract: () => 'wooden floors' },
	{ pattern: /laminate\s+(?:floors?|flooring)/gi, extract: () => 'laminate flooring' },
	{ pattern: /under[- ]?floor\s+heating/gi, extract: () => 'underfloor heating' },
	{ pattern: /juliet\s+balcony/gi, extract: () => 'juliet balcony' },
	{ pattern: /\bbalcony\b/gi, extract: () => 'balcony' },
	{ pattern: /french\s+doors/gi, extract: () => 'french doors' },
	{ pattern: /patio\s+doors/gi, extract: () => 'patio doors' },
	{ pattern: /bi[- ]?fold\s+doors/gi, extract: () => 'bi-fold doors' },
	{ pattern: /alarm\s+system/gi, extract: () => 'alarm system' },
	{ pattern: /security\s+system/gi, extract: () => 'security system' },
	{ pattern: /video\s+(?:door\s+)?(?:entry|intercom)/gi, extract: () => 'video entry' },
	{ pattern: /communal\s+(?:garden|grounds)/gi, extract: () => 'communal gardens' },
	{ pattern: /residents?\s+(?:parking|gym|lounge)/gi, extract: (m) => `residents ${m[0]?.split(/\s+/)[1]?.toLowerCase() ?? 'amenities'}` },
	{ pattern: /concierge/gi, extract: () => 'concierge' },
	{ pattern: /lift\s+access/gi, extract: () => 'lift access' },
	{ pattern: /wheelchair\s+access/gi, extract: () => 'wheelchair accessible' },
	{ pattern: /ground\s+floor/gi, extract: () => 'ground floor' },
	{ pattern: /first\s+floor(?:\s+flat)?/gi, extract: () => 'first floor' },
	{ pattern: /top\s+floor/gi, extract: () => 'top floor' },
	{ pattern: /penthouse/gi, extract: () => 'penthouse' },
	{ pattern: /maisonette/gi, extract: () => 'maisonette' },
	{ pattern: /duplex/gi, extract: () => 'duplex' },
	{ pattern: /split[- ]?level/gi, extract: () => 'split-level' },
	{ pattern: /two\s+reception\s+rooms?/gi, extract: () => 'two reception rooms' },
	{ pattern: /separate\s+(?:dining|living)\s+room/gi, extract: (m) => `separate ${m[0]?.split(/\s+/)[1]?.toLowerCase() ?? 'room'}` },
	{ pattern: /breakfast\s+(?:room|bar|area)/gi, extract: () => 'breakfast area' },
	{ pattern: /study(?:\s+room)?/gi, extract: () => 'study' },
	{ pattern: /home\s+office/gi, extract: () => 'home office' },
	{ pattern: /annexe/gi, extract: () => 'annexe' },
	{ pattern: /granny\s+flat/gi, extract: () => 'annexe' },
	{ pattern: /self[- ]?contained/gi, extract: () => 'self-contained' },

	// Location benefits
	{ pattern: /(?:near|close\s+to|walking\s+distance\s+(?:to|from)?)\s+(?:train\s+)?station/gi, extract: () => 'near station' },
	{ pattern: /(?:near|close\s+to|walking\s+distance\s+(?:to|from)?)\s+(?:town\s+)?centre/gi, extract: () => 'near town centre' },
	{ pattern: /(?:near|close\s+to|walking\s+distance\s+(?:to|from)?)\s+shops?/gi, extract: () => 'near shops' },
	{ pattern: /(?:near|close\s+to|walking\s+distance\s+(?:to|from)?)\s+schools?/gi, extract: () => 'near schools' },
	{ pattern: /(?:near|close\s+to)\s+(?:the\s+)?(?:hospital|university|park)/gi, extract: (m) => `near ${m[0]?.split(/\s+/).slice(-1)[0]?.toLowerCase() ?? 'amenities'}` },
	{ pattern: /quiet\s+(?:cul[- ]?de[- ]?sac|street|location|area)/gi, extract: () => 'quiet location' },
	{ pattern: /cul[- ]?de[- ]?sac/gi, extract: () => 'cul-de-sac' },
	{ pattern: /no\s+through\s+road/gi, extract: () => 'cul-de-sac' },
	{ pattern: /village\s+(?:location|centre)/gi, extract: () => 'village location' },
	{ pattern: /rural\s+(?:location|setting)/gi, extract: () => 'rural setting' },
	{ pattern: /countryside\s+views?/gi, extract: () => 'countryside views' },
	{ pattern: /sea\s+views?/gi, extract: () => 'sea views' },
	{ pattern: /river\s+views?/gi, extract: () => 'river views' },
	{ pattern: /park\s+views?/gi, extract: () => 'park views' },
	{ pattern: /overlook(?:ing|s)?\s+(?:the\s+)?(?:park|gardens?|fields?)/gi, extract: () => 'overlooks green space' },
	{ pattern: /tree[- ]?lined\s+(?:street|road)/gi, extract: () => 'tree-lined street' },

	// Red flags
	{ pattern: /above\s+(?:commercial|shop|retail)\s+premises/gi, extract: () => 'above commercial premises' },
	{ pattern: /shared\s+(?:entrance|hallway|access)/gi, extract: () => 'shared entrance' },
	{ pattern: /communal\s+entrance/gi, extract: () => 'shared entrance' },
	{ pattern: /zero\s+deposit/gi, extract: () => 'zero deposit scheme' },
	{ pattern: /short\s+let(?:\s+only)?/gi, extract: () => 'short let only' },
	{ pattern: /no\s+(?:dss|benefits?|housing\s+benefit)/gi, extract: () => 'no benefits' },
	{ pattern: /professionals?\s+only/gi, extract: () => 'professionals only' },
	{ pattern: /no\s+(?:children|families)/gi, extract: () => 'no children' },
	{ pattern: /over\s+\d+s?\s+only/gi, extract: () => 'age restriction' },
	{ pattern: /student\s+(?:let|property|accommodation)/gi, extract: () => 'student let' },
	{ pattern: /busy\s+road/gi, extract: () => 'busy road' },
	{ pattern: /main\s+road/gi, extract: () => 'main road location' },
	{ pattern: /flight\s+path/gi, extract: () => 'flight path' },
	{ pattern: /housing\s+association/gi, extract: () => 'housing association' },
	{ pattern: /council\s+(?:property|flat|house)/gi, extract: () => 'council property' },
	{ pattern: /ex[- ]?council/gi, extract: () => 'ex-council' },

	// Heating/utilities
	{ pattern: /gas\s+central\s+heating/gi, extract: () => 'gas central heating' },
	{ pattern: /oil[- ]?fired\s+(?:central\s+)?heating/gi, extract: () => 'oil heating' },
	{ pattern: /electric\s+(?:storage\s+)?heaters?/gi, extract: () => 'electric heating' },
	{ pattern: /(?:lpg|bottled)\s+gas/gi, extract: () => 'lpg heating' },
	{ pattern: /biomass\s+(?:boiler|heating)/gi, extract: () => 'biomass heating' },
	{ pattern: /heat\s+pump/gi, extract: () => 'heat pump' },
	{ pattern: /air\s+conditioning/gi, extract: () => 'air conditioning' },
	{ pattern: /double\s+glaz(?:ing|ed)/gi, extract: () => 'double glazing' },
	{ pattern: /triple\s+glaz(?:ing|ed)/gi, extract: () => 'triple glazing' },
	{ pattern: /upvc\s+(?:windows|doors)/gi, extract: () => 'upvc windows' },
	{ pattern: /solar\s+panels?/gi, extract: () => 'solar panels' },
	{ pattern: /smart\s+(?:meter|thermostat)/gi, extract: () => 'smart heating' },
	{ pattern: /combi\s+boiler/gi, extract: () => 'combi boiler' },
	{ pattern: /new\s+boiler/gi, extract: () => 'new boiler' },

	// Pets/tenancy
	{ pattern: /pets?\s+(?:considered|allowed|welcome|friendly|negotiable)/gi, extract: () => 'pets considered' },
	{ pattern: /no\s+pets?/gi, extract: () => 'no pets' },
	{ pattern: /(?:minimum|min\.?)\s+(\d+)\s+(?:month|year)\s+(?:tenancy|let|ast)/gi, extract: (m) => `minimum ${m[1]} ${m[0]?.includes('year') ? 'year' : 'month'} tenancy` },
	{ pattern: /long[- ]?term\s+(?:let|tenancy|rental)/gi, extract: () => 'long-term let' },
	{ pattern: /un[- ]?furnished/gi, extract: () => 'unfurnished' },
	{ pattern: /part[- ]?furnished/gi, extract: () => 'part-furnished' },
	{ pattern: /(?:^|\s)furnished(?:$|\s|[.,;:!,])/gi, extract: () => 'furnished' },

	// Other notable features
	{ pattern: /(\d+)\s*(?:sq\s*ft|sqft|square\s+feet)/gi, extract: () => null },
	{ pattern: /council\s+tax\s+band\s+([a-h])/gi, extract: (m) => `council tax band ${m[1]?.toLowerCase() ?? '?'}` },
	{ pattern: /bills?\s+included/gi, extract: () => 'bills included' },
	{ pattern: /water\s+(?:rates?\s+)?included/gi, extract: () => 'water included' },
];

/**
 * Category order for sorting notes by importance
 */
export const CATEGORY_ORDER = [
	'recently',
	'newly',
	'fully',
	'freshly',
	'brand',
	'new',
	'south',
	'west',
	'east',
	'north',
	'garden',
	'patio',
	'deck',
	'driveway',
	'parking',
	'garage',
	'bay',
	'period',
	'high ceiling',
	'en-suite',
	'utility',
	'near',
	'quiet',
	'village',
	'rural',
	'above',
	'shared',
	'zero',
	'no pet',
	'gas',
	'electric',
	'oil',
	'double',
	'triple',
	'pet',
	'furnished',
	'minimum',
];
