[package]
name = "let-tui"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[[bin]]
name = "let-tui"
path = "src/main.rs"

[dependencies]
let-sdk = { path = "../let-sdk" }
chrono = { workspace = true }
crossterm = { workspace = true }
image = { workspace = true }
base64-simd = { workspace = true }
ratatui = { workspace = true }
ratatui-image = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
url = { workspace = true }
tracing = { workspace = true }
